version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  target-branch: update-dependency
  ignore:
  - dependency-name: firebase
    versions:
    - 8.2.10
    - 8.2.3
    - 8.2.8
    - 8.2.9
    - 8.3.0
    - 8.3.1
  - dependency-name: primereact
    versions:
    - 6.0.0
    - 6.1.0
    - 6.2.1
  - dependency-name: reactstrap
    versions:
    - 8.8.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
