export const CREATE_USER_START = 'CREATE_USER_START'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL'

export const FETCH_USERS_START = 'FETCH_USERS_START'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL'

export const UPDATE_USER_START = 'UPDATE_USER_START'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'

export const FETCH_ISBN_START = 'FETCH_ISBN_START'
export const FETCH_ISBN_SUCCESS = 'FETCH_ISBN_SUCCESS'
export const FETCH_ISBN_FAIL = 'FETCH_ISBN_FAIL'

export const FETCH_BOOKS_START = 'FETCH_BOOKS_START'
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS'
export const FETCH_BOOKS_FAIL = 'FETCH_BOOKS_FAIL'

export const FETCH_ISSUEDBOOKS_START = 'FETCH_ISSUEDBOOKS_START'
export const FETCH_ISSUEDBOOKS_SUCCESS = 'FETCH_ISSUEDBOOKS_SUCCESS'
export const FETCH_ISSUEDBOOKS_FAIL = 'FETCH_ISSUEDBOOKS_FAIL'

export const DELETE_BOOK_START = 'DELETE_BOOK_START'
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS'
export const DELETE_BOOK_FAIL = 'DELETE_BOOK_FAIL'

export const ISSUE_BOOK_START = 'ISSUE_BOOK_START'
export const ISSUE_BOOK_SUCCESS = 'ISSUE_BOOK_SUCCESS'
export const ISSUE_BOOK_FAIL = 'ISSUE_BOOK_FAIL'

export const RETURN_BOOK_START = 'RETURN_BOOK_START'
export const RETURN_BOOK_SUCCESS = 'RETURN_BOOK_SUCCESS'
export const RETURN_BOOK_FAIL = 'RETURN_BOOK_FAIL'

export const RENEW_BOOK_START = 'RENEW_BOOK_START'
export const RENEW_BOOK_SUCCESS = 'RENEW_BOOK_SUCCESS'
export const RENEW_BOOK_FAIL = 'RENEW_BOOK_FAIL'

export const ADD_BOOK_START = 'ADD_BOOK_START'
export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS'
export const ADD_BOOK_FAIL = 'ADD_BOOK_FAIL'

export const UPDATE_BOOK_START = 'UPDATE_BOOK_START'
export const UPDATE_BOOK_SUCCESS = 'UPDATE_BOOK_SUCCESS'
export const UPDATE_BOOK_FAIL = 'UPDATE_BOOK_FAIL'

export const UPLOAD_BOOK_IMAGE_START = 'UPLOAD_BOOK_IMAGE_START'
export const UPLOAD_BOOK_IMAGE_PROGRESS = 'UPLOAD_BOOK_IMAGE_PROGRESS'
export const UPLOAD_BOOK_IMAGE_SUCCESS = 'UPLOAD_BOOK_IMAGE_SUCCESS'
export const UPLOAD_BOOK_IMAGE_FAIL = 'UPLOAD_BOOK_IMAGE_FAIL'

export const UPLOAD_USER_IMAGE_START = 'UPLOAD_USER_IMAGE_START'
export const UPLOAD_USER_IMAGE_PROGRESS = 'UPLOAD_USER_IMAGE_PROGRESS'
export const UPLOAD_USER_IMAGE_SUCCESS = 'UPLOAD_USER_IMAGE_SUCCESS'
export const UPLOAD_USER_IMAGE_FAIL = 'UPLOAD_USER_IMAGE_FAIL'

export const UPDATE_BOOK_REVIEW_START = 'UPDATE_BOOK_REVIEW_START';
export const UPDATE_BOOK_REVIEW_SUCCESS = 'UPDATE_BOOK_REVIEW_SUCCESS';
export const UPDATE_BOOK_REVIEW_FAIL = 'UPDATE_BOOK_REVIEW_FAIL';

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'
